SELECT * FROM PAYMENT WHERE TYPE_ID = 4;
SELECT * FROM MARK WHERE SUBJECT_ID = 1;
SELECT DISTINCT * FROM STUDENT join PUBLIC.PAYMENT P2 on STUDENT.ID = P2.STUDENT_ID WHERE TYPE_ID = 2;
SELECT DISTINCT * FROM STUDENT JOIN PUBLIC.MARK M on STUDENT.ID = M.STUDENT_ID WHERE SUBJECT_ID = 5;