SELECT * FROM payment WHERE AMOUNT >= 500;
SELECT * FROM STUDENT WHERE BIRTHDAY < DATEADD(YEAR , -20, DATE'2000-10-10');
SELECT * FROM STUDENT WHERE BIRTHDAY > DATEADD(YEAR , -20, DATE'2000-10-10') AND GROUPNUMBER = 10;
SELECT * FROM STUDENT WHERE GROUPNUMBER IN (4,5,6) OR NAME LIKE 'Mike%';
SELECT * FROM PAYMENT WHERE PAYMENT_DATE BETWEEN DATEADD(MONTH , -8, DATE'2000-10-10') AND DATE'2000-10-10';
SELECT * FROM STUDENT WHERE NAME LIKE 'A%';
SELECT * FROM STUDENT WHERE (NAME LIKE 'Roxi%' AND GROUPNUMBER = 4) OR (NAME LIKE 'Tallie%' AND GROUPNUMBER = 9);

