ALTER TABLE STUDENT ALTER COLUMN BIRTHDAY SET NOT NULL;
ALTER TABLE MARK ADD CONSTRAINT MARK_RANGE CHECK ("MARK" BETWEEN 0 and 10);
ALTER TABLE MARK ALTER COLUMN STUDENT_ID SET NOT NULL;
ALTER TABLE MARK ALTER COLUMN SUBJECT_ID SET NOT NULL;
ALTER TABLE SUBJECT ADD CONSTRAINT GRADE_RANGE CHECK ("GRADE" BETWEEN 1 and 5);
ALTER TABLE PAYMENTTYPE ADD CONSTRAINT NAME_UNQ unique (NAME);
ALTER TABLE PAYMENT ALTER COLUMN TYPE_ID SET NOT NULL;
ALTER TABLE PAYMENT ALTER COLUMN AMOUNT SET NOT NULL;


