SELECT MAX(STUDENT.BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT.PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK.MARK) FROM MARK WHERE SUBJECT_ID IN (SELECT ID FROM SUBJECT WHERE NAME LIKE 'Math');
SELECT MIN(PAYMENT.AMOUNT) FROM PAYMENT WHERE TYPE_ID = 2;