SELECT MIN(STUDENT.BIRTHDAY) FROM STUDENT;
SELECT MIN(PAYMENT.PAYMENT_DATE) FROM PAYMENT;
SELECT AVG(MARK.MARK) FROM MARK WHERE SUBJECT_ID = 5;
SELECT AVG(PAYMENT.AMOUNT) FROM PAYMENT WHERE TYPE_ID = 2;