SELECT NAME , AVG(MARK) FROM STUDENT INNER JOIN PUBLIC.MARK M on STUDENT.ID = M.STUDENT_ID GROUP BY NAME HAVING AVG(MARK)> 8;
SELECT STUDENT.ID, NAME , MIN(MARK) FROM STUDENT INNER JOIN PUBLIC.MARK M on STUDENT.ID = M.STUDENT_ID GROUP BY NAME HAVING MIN(MARK)> 7;
SELECT STUDENT.ID, STUDENT.NAME FROM STUDENT WHERE ID IN (SELECT PAYMENT.STUDENT_ID FROM PAYMENT where YEAR(PAYMENT_DATE) = '2019' GROUP BY STUDENT_ID HAVING COUNT(PAYMENT.STUDENT_ID) >= 2);
