UPDATE SUBJECT SET GRADE = 5 WHERE NAME LIKE 'End of Suburbia: Oil Depletion and the Collapse of the American Dream';
UPDATE STUDENT SET GROUPNUMBER = 8 WHERE NAME LIKE 'Tremaine Worvill';
UPDATE PAYMENT SET AMOUNT = 500, STUDENT_ID = 2 WHERE PAYMENT_DATE > DATE'2021-01-01' AND TYPE_ID = 2;
UPDATE MARK SET MARK = 2 WHERE SUBJECT_ID = 315;