SELECT * FROM SUBJECT WHERE ID IN (SELECT MARK.SUBJECT_ID FROM MARK GROUP BY SUBJECT_ID HAVING AVG(MARK.MARK) > (SELECT AVG(MARK.MARK) FROM MARK));
SELECT * FROM STUDENT WHERE ID IN (SELECT PAYMENT.STUDENT_ID FROM PAYMENT GROUP BY STUDENT_ID HAVING AVG(PAYMENT.AMOUNT) < (SELECT AVG(PAYMENT.AMOUNT) FROM PAYMENT));
